import ThemeRegistry from "@/components/reuseable/ThemeRegistry";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import AppBar from "../components/appbar/AppBar";
import ScopedCssBaseline from "@mui/material/ScopedCssBaseline";
import Footer from "@/components/appbar/Footer";
export const metadata = {
  title: "Nxnews",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body suppressHydrationWarning={true}>
          <ScopedCssBaseline>
            <AppBar />
            {children}
            <Footer />
          </ScopedCssBaseline>
        </body>
      </ThemeRegistry>
    </html>
  );
}
